import 'package:btg_funds_app/features/user/domain/domain.dart' show ActiveSubscriptionEntity;
import 'package:json_annotation/json_annotation.dart';

part 'active_subscription_dto.g.dart';

/// Data Transfer Object representing an active fund subscription in the API response layer.
///
/// This DTO is part of the data layer and is responsible for serializing
/// and deserializing active subscription information from API responses. It maps
/// to the [ActiveSubscriptionEntity] in the domain layer, providing the bridge
/// between external data sources and the application's business logic.
///
/// The [ActiveSubscriptionDto] is typically received from API calls as part of
/// user profile data and converted to an [ActiveSubscriptionEntity] for use
/// throughout the application.
@JsonSerializable()
class ActiveSubscriptionDto {
  /// Creates a new [ActiveSubscriptionDto] instance.
  ///
  /// All parameters are required and define the subscription's core information:
  /// - [fundId]: The unique identifier of the investment fund being subscribed to
  /// - [fundName]: The display name of the investment fund
  /// - [amount]: The monetary value invested in the fund
  /// - [subscribedAt]: The date and time string when the subscription was created,
  ///   corresponding to the `subscribed_at` field in the API response
  const ActiveSubscriptionDto({
    required this.fundId,
    required this.fundName,
    required this.amount,
    required this.subscribedAt,
  });

  /// Constructs an [ActiveSubscriptionDto] instance from a JSON map.
  ///
  /// Deserializes the provided JSON [json] map into an [ActiveSubscriptionDto] instance,
  /// handling field name transformations as specified by [JsonKey] annotations.
  /// This factory method is automatically generated by the json_serializable package.
  factory ActiveSubscriptionDto.fromJson(Map<String, dynamic> json) =>
      _$ActiveSubscriptionDtoFromJson(json);

  /// The unique identifier of the investment fund.
  ///
  /// Corresponds to the `fund_id` field in the JSON response.
  @JsonKey(name: 'fund_id')
  final String fundId;

  /// The display name of the investment fund.
  ///
  /// Corresponds to the `fund_name` field in the JSON response.
  @JsonKey(name: 'fund_name')
  final String fundName;

  /// The monetary value invested in the fund.
  ///
  /// Represents the amount of money the user has allocated to this fund subscription,
  /// typically in the system's base currency (e.g., Colombian Pesos - COP).
  final double amount;

  /// The date and time when the subscription was created.
  ///
  /// Corresponds to the `subscribed_at` field in the JSON response.
  /// Stored as a string in ISO 8601 format or another standard date format
  /// as provided by the API.
  @JsonKey(name: 'subscribed_at')
  final String subscribedAt;

  /// Converts this [ActiveSubscriptionDto] instance to a JSON map.
  ///
  /// Serializes the instance into a JSON-compatible map, applying any
  /// field name transformations as specified by [JsonKey] annotations.
  /// This method is automatically generated by the json_serializable package.
  Map<String, dynamic> toJson() => _$ActiveSubscriptionDtoToJson(this);
}
