import 'package:btg_funds_app/features/user/data/data.dart' show ActiveSubscriptionDto;
import 'package:btg_funds_app/features/user/domain/domain.dart' show UserEntity;
import 'package:json_annotation/json_annotation.dart';

part 'user_dto.g.dart';

/// Data Transfer Object representing a user in the API response layer.
///
/// This DTO is part of the data layer and is responsible for serializing
/// and deserializing user information from API responses. It maps to the
/// [UserEntity] in the domain layer, providing the bridge between external
/// data sources and the application's business logic.
///
/// The [UserDto] is typically received from API calls and converted to a
/// [UserEntity] for use throughout the application.
@JsonSerializable()
class UserDto {
  /// Creates a new [UserDto] instance.
  ///
  /// All parameters are required and define the user's core information:
  /// - [id]: The unique identifier of the user
  /// - [name]: The full name of the user
  /// - [balance]: The current account balance (in the system's currency/units)
  /// - [activeSubscriptions]: A list of active fund subscriptions for the user,
  ///   corresponding to the `active_subscriptions` field in the API response
  const UserDto({
    required this.id,
    required this.name,
    required this.balance,
    required this.activeSubscriptions,
  });

  /// Constructs a [UserDto] instance from a JSON map.
  ///
  /// Deserializes the provided JSON [json] map into a [UserDto] instance,
  /// handling field name transformations as specified by [JsonKey] annotations.
  /// This factory method is automatically generated by the json_serializable package.
  factory UserDto.fromJson(Map<String, dynamic> json) => _$UserDtoFromJson(json);

  /// The unique identifier of the user.
  final String id;

  /// The full name of the user.
  final String name;

  /// The current account balance of the user.
  ///
  /// Represents the available funds in the user's account, typically in the
  /// system's base currency (e.g., Colombian Pesos - COP).
  final double balance;

  /// A list of active fund subscriptions for the user.
  ///
  /// Corresponds to the `active_subscriptions` field in the JSON response.
  /// Each element represents an active investment subscription with fund details
  /// and subscription metadata.
  @JsonKey(name: 'active_subscriptions')
  final List<ActiveSubscriptionDto> activeSubscriptions;

  /// Converts this [UserDto] instance to a JSON map.
  ///
  /// Serializes the instance into a JSON-compatible map, applying any
  /// field name transformations as specified by [JsonKey] annotations.
  /// This method is automatically generated by the json_serializable package.
  Map<String, dynamic> toJson() => _$UserDtoToJson(this);
}
